version: "3"

services:
  postgresdb:
    image: postgres:latest
    container_name: passkeeper-db
    environment:
    - POSTGRES_PASSWORD=felipe123
    - POSTGRES_DB=passkeeper
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - app-database

  backend:
    image: node:16.2-alpine
    container_name: passkeeper-backend
    entrypoint: yarn workspace @graphql-lab/backend run start:dev
    depends_on:
    - postgresdb
    ports:
    - "4000:4000"
    working_dir: /workspace
    volumes:
    - .:/workspace
    networks:
    - app-database

volumes:
  postgres_data:

networks:
  app-database:
